### ISSUE TITLE
Loading while waiting for API

### ISSUE THREAD

**Issue by ChanAbay-abay** [ian-sobs/KURIPOT#113]
Please use this component from DaisyUI for the loading. Any one of the lines will do, the only difference is the size.

`<span className="loading loading-dots loading-xs"></span>`
`<span className="loading loading-dots loading-sm"></span>`
`<span className="loading loading-dots loading-md"></span>`
`<span className="loading loading-dots loading-lg"></span>`

What it looks like:
![image](https://github.com/user-attachments/assets/f8eac381-758d-42d9-b742-efaef34945f6)

Reference: Loading dots
https://daisyui.com/components/loading/

### Pages where loading might be needed
for pages that fetch data and have to be rendered on the frontend
- [ ] Dashboard -> Dashboard.jsx
- [x] Manage Accounts -> ViewAccounts.jsx
- [x] My Categories -> Category.jsx
- [x] Budgets Page ->BudgetsPage.jsx
- [ ] Transactions Page
- [ ] Reports Page

**Comment by elyzuh** [comment]
slei oke i have it ready in a branch na but ill push to main once i added the loading to all possible pages where fetching data is needed
