### ISSUE TITLE
Dashboard recent transactions improvement

### ISSUE THREAD

**Issue by ian-sobs** [ian-sobs/KURIPOT#114]
- [x] A recent transaction must show the account it is from
- [ ] A recent transaction must show its category (debatable)
- [x] fix date display. make it exactly the same as the one sa Transaction Daily

**Comment by ChanAbay-abay** [comment]
@ian-sobs fixed the first two. idk if we should show category na for the transactions kay its looking kinda clumped. and i guess the show of category adds more separation between Recent Transactions and TransactionsPage. Final call is up to you, feel free to close the issue if you're okay with how it currently is. Arigathankyou

Note: I opened 2 new issues after adding some of the things you requested here.
![image](https://github.com/user-attachments/assets/09fe1dc5-0363-4d9c-80f8-6933b2efda06)
