### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by elyzuh** [ian-sobs/KURIPOT#117]
- [x] reports page needs better layout
- [x] on dashboard, maybe edit the "no spending data available" opacity or make it smaller, same goes for the other similar stuff sa page
- [x] transactions pagea, maybe make the line the accent color nato(like thebright purple) HFJJHKFAJ the line i mean kanang page indicator kung onsa ka na tab

das all i hv for now methinsk

**Comment by ChanAbay-abay** [comment]
@elyzuh For review of the Reports Page. Please check the PR I requested for your review.

![image](https://github.com/user-attachments/assets/40aefd8b-1b2b-41d5-92cb-4529045457eb)
